server:
  port: 9001
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyzw/config_resp.git
          searchPaths: '{application}'
          username: lyz_w@163.com
          password: zhouwei123
eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
